api_file_create:
  path: /api/file
  controller: App\Controller\FileController::createAction
  methods: POST

api_file_get_info:
  path: /api/file-info/
  controller: App\Controller\FileController::getAllInfoAction
  methods: GET

api_file_get:
  path: /api/file/{filename}
  controller: App\Controller\FileController::getFileAction
  methods: GET

api_file_delete:
  path: /api/file/{filename}
  controller: App\Controller\FileController::removeAction
  methods: DELETE

#api_file_get_info:
#  path: /api/file-info/{fileName}
#  controller: App\Controller\FileController::getInfoAction
#  methods: GET

health:
  path: /health
  controller: App\Controller\HealthController::getAction
  methods: GET